[theme]
# Primary accent color for interactive elements.
primaryColor = "#1abc9c"

# Background color for the main content area.
backgroundColor = "#00415a"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"